### ISSUE TITLE
Start profiler with a unique SSID

### ISSUE THREAD

**Issue by adriangranados** [WLAN-Pi/profiler#96]
Similar to bluetooth, use a unique SSID (e.g., wlanpi_profiler-XXX)

**Comment by joshschmelzle** [comment]
Based on Slack discussions, the ask is to change the default SSID to `Profiler xxx` where `xxx` represents the last 3 characters of the eth0 MAC address in lower case. The first letter of `Profiler` will be upper case where the rest of the word is lower case. The separator will be a single space with no trailing characters after the 3 character identifier.

**Comment by adriangranados** [comment]
Yes, that's correct. I created the issue before we settled on a naming convention and never got back to update it.

**Comment by joshschmelzle** [comment]
Suggested behavior: 

* Change the default SSID value in `config.ini` to blank (nothing).
* Precedence:
  * if value in config.ini is blank, profiler will generate `Profiler XXX` as the SSID (where XXX is the last 3 characters of the eth0 MAC address)
  * if value in config.ini is not blank, use the set value in config.ini as the SSID.
  * if value in config.ini is not blank, and user provides SSID from arg, use CLI provided SSID
 
Additionally, the SSID which will be used for beaconing will need to be saved to /var/run/wlanpi-profiler.ssid if profiler starts in beaconing mode. Otherwise, do nothing. (see #101)

**Comment by adriangranados** [comment]
When the user provides an SSID as an arg, I guess the value (blank or not) in config.ini is irrelevant, correct?

**Comment by joshschmelzle** [comment]
Yes, if the user explicitly provides an SSID by passing it in, that takes the precedence over what is in config.ini.
